name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  python-tests:
    strategy:
      matrix:
        module: [synca.mcp.python]
      fail-fast: false
    
    uses: ./.github/workflows/_python_test.yml
    with:
      module_path: ${{ matrix.module }}
    secrets: inherit
